FROM node:20-alpine
RUN apk add --no-cache openjdk21-jre-headless curl
RUN npm install -g firebase-tools
WORKDIR /app
COPY firebase.json .
COPY firestore.rules .
EXPOSE 4000 8080 9099
CMD ["firebase", "emulators:start", "--only", "auth,firestore", "--project", "track-csce483"]
